Squashed commit of the following: feat: add Tech Stack section with marquee animation and 2 buttons for expanding/shrinking tech list
commit 2623de1d72aba72f0f4a9cab148d1b3788f9da99
Author: monsterchick <kwanho.app@gmail.com>
Date:   Thu Oct 9 12:42:34 2025 +0800

    Squashed commit of the following:
    fix: set src/app/page.tsx to UTF-8 on vscode bottom to fix issue:
    ./src/app/page.tsx
    Error: Failed to read source code from
    /home/runner/work/kylerlam.github.io/kylerlam.github.io/src/app/page.tsx
    Caused by:
        stream did not contain valid UTF-8

    commit b4252edfaf5f4164638aa994b0f94c7b379a3f6e
    Author: monsterchick <kwanho.app@gmail.com>
    Date:   Thu Oct 9 12:22:28 2025 +0800

        test: set src/app/page.tsx to UTF-8 on vscode

    commit 63358e241e4c2deebf73a4c4f67967833d2cea1f
    Author: monsterchick <kwanho.app@gmail.com>
    Date:   Thu Oct 9 12:18:54 2025 +0800

        test: updates

    commit 181a642482663b11632cd26f696ec51aa18af234
    Author: monsterchick <kwanho.app@gmail.com>
    Date:   Thu Oct 9 12:10:55 2025 +0800

        test: codex try to fix 'the workflow uses Node 14, which is incompatible with Next 14 and your lockfile (npm 10)'

    commit c4b7fe4f81bf06476f97648922f3b9641ee7cdd5
    Author: monsterchick <kwanho.app@gmail.com>
    Date:   Thu Oct 9 12:05:28 2025 +0800

        test: downgrade the node version on Github Action to fix ./src/app/page.tsx

    commit 602b304420c7550a04cfcaf770b1d36f01a4f401
    Author: monsterchick <kwanho.app@gmail.com>
    Date:   Thu Oct 9 11:57:48 2025 +0800

        test: tried to uninstall 'simple-react-map'

    commit 453bf42993ad7228cf4475767a92729f597f09b5
    Author: monsterchick <kwanho.app@gmail.com>
    Date:   Thu Oct 9 11:53:42 2025 +0800

        fix: codex tried to fix bugs to be able to pass deploy on Action

commit 51b0265465ffaae35b1bef426905f0056acfbe3a
Author: monsterchick <kwanho.app@gmail.com>
Date:   Thu Oct 9 11:24:28 2025 +0800

    feat: add Tech Stack section and set each tech into Marquee animation. With 2 buttons for expanding/shrinking tech

commit 7ca18d788bfb1d4cd7e5dae0e5dde9d3ce5083d0
Author: monsterchick <kwanho.app@gmail.com>
Date:   Wed Oct 8 21:52:10 2025 +0800

    chore: preparing environment for simple-react-map

commit 416f6aa2b8b0b7980ad7043e7f3e25e6726ac1e6
Author: monsterchick <kwanho.app@gmail.com>
Date:   Wed Oct 8 19:06:15 2025 +0800

    chore: reformat the project

commit 37ab4b8f74d44dd8e7923255668ac98cab9915ae
Author: monsterchick <kwanho.app@gmail.com>
Date:   Wed Oct 8 16:27:34 2025 +0800

    style: fix auto create new line when achieving default 80 words to be 200 words

commit 2467b2ed0e67e4cf95c6ada3bc60addc58d711f1
Author: monsterchick <kwanho.app@gmail.com>
Date:   Wed Oct 8 15:08:08 2025 +0800

    chore: recover codes for troubleshooting lazy load issue

commit b8aa52b71631bb0c181f1bda128479e747fcce7e
Author: monsterchick <kwanho.app@gmail.com>
Date:   Tue Oct 7 23:08:50 2025 +0800

    chore: install prettier to unify code style and bring some convenience